Config task
EleutherAI/lm-eval2 pull request #13
Opened 2023-03-10 04:05 UTC by lintangsutawika

2023-03-10 04:08 UTC, lintangsutawika commented
@haileyschoelkopf re-submitting the PR.

2023-03-11 14:14 UTC, haileyschoelkopf commented on lm_eval/tasks/__init__.py
> +    return "configurable_{dataset_path}_{dataset_name}".format(**task_config)
Would it maybe make sense to have the task names be the filename of the yaml file they use as config? Feel free to ignore

2023-03-27 18:27 UTC, haileyschoelkopf commented on examples/configurable_task/sglue_cb.yaml
> +has_validation_docs: true
I wonder if we want to not pass e.g. `has_training_docs` in the config and instead, assume these are true if the `training_split` value is a string, and have a user pass `none` to `training_split` if they want `has_training_docs: false`. 

Feel free to ignore if you think it's better to keep these sets of args separate though.

2023-03-27 18:39 UTC, haileyschoelkopf requested changes
Looks good! We can merge this once `aggregation` and `higher_is_better` aren't ignored.

I only saw a `greedy_until` implementation in this PR though. I think we should still merge it, but the rest need implementation

2023-03-27 18:39 UTC, haileyschoelkopf commented on lm_eval/api/task.py
> +        config={"num_fewshot": 0},
We need to generalize this `config` kwarg accepted by a non-configurable task. 

Is there a way to pass some task name to a TaskConfig, which makes a ConfigurableTask inherit from a given Task subclass instead of the base Task class? I think it's desirable for someone to be able to take a complex task and override only a couple fields in it. Does this make sense, or do you disagree that we should let someone override more fields than "num_fewshot" of an existing non-config task?

2023-03-27 18:39 UTC, haileyschoelkopf commented on lm_eval/api/task.py
> +                    metric_object = evaluate.load(metric_name)
This behavior is ok for this PR, but I'll add a METRIC_REGISTRY so that we can also use the metrics in `metrics.py` in configurable tasks.

2023-03-27 18:39 UTC, haileyschoelkopf commented on lm_eval/api/task.py
> +            aggregation_dict[key] = mean
This hardcodes "mean" as the aggregation for all metrics. Shouldn't this receive the value from your TaskConfig?

2023-03-27 18:39 UTC, haileyschoelkopf commented on lm_eval/api/task.py
> +            higher_is_better_dict[key] = True
Likewise, doesn't this ignore the actual `higher_is_better` field from your config?

2023-03-28 16:07 UTC, lintangsutawika commented on lm_eval/api/task.py
> +        config={"num_fewshot": 0},
I think there could be a way to do this (combining other Task object with configs) but I think it's probably better to do it in a separate PR and I can get right to it after we merge this one.

2023-03-28 16:08 UTC, lintangsutawika commented on lm_eval/api/task.py
> +            aggregation_dict[key] = mean
Made a `METRIC_REGISTRY` to help with this.

2023-03-28 16:08 UTC, lintangsutawika commented on lm_eval/api/task.py
> +            higher_is_better_dict[key] = True
Made an `AGGREGATION_REGISTRY` for this.

2023-03-28 16:09 UTC, lintangsutawika commented
@haileyschoelkopf thanks for the feedback. there are a few things I missed that you brought up. I've addressed them in the most recent push.

2023-03-29 01:59 UTC, haileyschoelkopf approved these changes
Looks good! We might want to change how the `metric_list` gets parsed in future ( a little unclear what the list of 3 elements in the config file mean to a novice) but looks great aside from that!!

2023-03-29 01:59 UTC, merged

2023-03-29 02:16 UTC, lintangsutawika commented
I'll make a new PR to make some options for `metric_list`